### ISSUE TITLE
Retries failed when aws-sdk-go not able to send the request and s5cmd stuck

### ISSUE THREAD

**Issue by charz** [peak/s5cmd#554]
Just saw the s5cmd is doing some retries, but it stuck when [aws-sdk-go ](https://github.com/aws/aws-sdk-go/blob/main/aws/corehandlers/handlers.go#L164) raised `send request failed`. 

```
cp s3://test/object
DEBUG retryable error: RequestError: send reqeust failed
caused by : GET "https://test-server/test/object": EOF
```

```
	if shouldRetry && req.Error != nil {
		err := fmt.Errorf("retryable error: %v", req.Error)
		msg := log.DebugMessage{Err: err.Error()}
		log.Debug(msg)
	}
```

From aws-sdk-go

```
	// Catch all request errors, and let the default retrier determine
	// if the error is retryable.
	r.Error = awserr.New(request.ErrCodeRequestError, "send request failed", err)
```

**Comment by PDD777** [comment]
It appears that this might be similar to what I'm finding as well.

I'm copying 2 dirs within the bucket, and some files I would get an "unexpected EOF" error, this was using the sync command, with only the --endpoint-url set, as we use Linode and not the very very pricey AWS.

Thinking that it might be the files, I tried a few files individually, no error, which confirms, not the file or the endpoints.

So I moved to the cp -n -u -s command, got this today.

Same "unexpected EOF" error on some files, but it spat out this as well.

<cut>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xa35623]

goroutine 81859 [running]:
github.com/peak/s5cmd/v2/command.Copy.shouldOverride({0xc0000a1400, 0xc0000a15e0, {0xb8d255, 0x2}, {0xc0000dcfc0, 0x68}, 0x0, 0x1, 0x1, 0x1, ...}, ...)
        /home/runner/work/s5cmd/s5cmd/command/cp.go:850 +0x1a3
github.com/peak/s5cmd/v2/command.Copy.doDownload({0xc0000a1400, 0xc0000a15e0, {0xb8d255, 0x2}, {0xc0000dcfc0, 0x68}, 0x0, 0x1, 0x1, 0x1, ...}, ...)
        /home/runner/work/s5cmd/s5cmd/command/cp.go:613 +0x118
github.com/peak/s5cmd/v2/command.Copy.prepareDownloadTask.func1()
        /home/runner/work/s5cmd/s5cmd/command/cp.go:567 +0xf3
github.com/peak/s5cmd/v2/parallel.(*Manager).Run.func1()
        /home/runner/work/s5cmd/s5cmd/parallel/parallel.go:57 +0x8a
created by github.com/peak/s5cmd/v2/parallel.(*Manager).Run
        /home/runner/work/s5cmd/s5cmd/parallel/parallel.go:53 +0xca

</cut>

It looks like a mem leak, and for large copies the application fails to release malloc to proceed in the cp process.

The system we are running this on has:
RAM: 8GB
CPU Cores: 2x2
Node: Proxmox VM

s5cmd version
v2.2.2-48f7e59

We are trying to cp 6+TB/25000 objects as an offsite backup location from s3 to local NFS store.
